#!/usr/bin/env bash
# Regenerate docs/upstream-diff/ — the READ-ONLY view of what kicad-patches/kicad/** changes
# against the pinned upstream KiCad (the kicad-python submodule).
#
# kicad-patches/kicad/** holds full copies of the upstream files we modify; those full copies
# are the only source and the only build input (build_rl_router.sh overlays them — it never
# reads this directory, and it never will). This script emits one unified diff per modified
# file so a reader sees exactly what changed, then PROVES the view by applying every diff to
# the pristine tree and requiring the result to be byte-identical to the full copies.
#
#   bash tools/make_upstream_diff.sh [OUT_DIR]     # default: docs/upstream-diff (run from anywhere)
#
# Output layout (all generated — do not edit; the check in the environment repository's
# tools/docs/check_docs.py regenerates and byte-compares it):
#   OUT_DIR/README.md              what this directory is
#   OUT_DIR/<rel>.diff             one unified diff per modified upstream file (`patch -p1` form)
#   OUT_DIR/NEW_FILES.txt          kicad-patches/kicad/** files with no upstream counterpart
# Files under kicad-patches/rl/** are our own sources, not upstream modifications — they are
# outside the scope of this view by construction.

set -euo pipefail
# Drop any git context inherited from a caller (git sets GIT_DIR & co. for every hook, and in a
# linked worktree that points at the main repository's admin directory). This script discovers the
# repository from its own location; with GIT_DIR set, the `git ls-files` below enumerates almost
# nothing and the generated view silently comes out empty.
unset GIT_DIR GIT_WORK_TREE GIT_INDEX_FILE GIT_OBJECT_DIRECTORY GIT_COMMON_DIR
cd "$(cd "$(dirname "$0")/.." && pwd)"          # the engine's root

OUT="${1:-docs/upstream-diff}"
PATCHED_ROOT="kicad-patches/kicad"
UPSTREAM_ROOT="kicad-python/kicad"
BANNER="# GENERATED by tools/make_upstream_diff.sh — for reading only, not a build input; see README.md in this directory."

[ -d "$UPSTREAM_ROOT/pcbnew" ] || { echo "ERROR: upstream not checked out at $UPSTREAM_ROOT (git submodule update --init --recursive)" >&2; exit 2; }
rm -rf "$OUT"
mkdir -p "$OUT"
: > "$OUT/NEW_FILES.txt"
cat > "$OUT/README.md" <<'EOF'
# upstream-diff — what this engine changes in KiCad (read-only view)

Every file here is **generated** by `tools/make_upstream_diff.sh` from the full copies in
`kicad-patches/kicad/` (our modified upstream files, the only source) and the pristine
upstream checkout in `kicad-python/` (the pinned submodule). One unified diff per modified
file, in `patch -p1` form, so a reader sees exactly which lines this engine changes.

- **Do not edit** anything in this directory; edit the full copy under `kicad-patches/kicad/`
  and re-run the script. The environment repository's doc checker regenerates this view and
  fails when it differs from the tracked files.
- **The build never reads this directory.** `build_rl_router.sh` overlays the full copies onto
  the upstream sources; there is no patch-apply path and no fallback.
- The view is proved on every regeneration: applying every diff to the pristine upstream
  files must reproduce the full copies byte for byte.
- Files under `kicad-patches/rl/` are this engine's own sources (not modified upstream files)
  and are therefore not listed here.
EOF

n_patch=0 n_new=0 n_same=0 patch_lines=0 full_lines=0
while IFS= read -r f; do
  rel="${f#$PATCHED_ROOT/}"
  up="$UPSTREAM_ROOT/$rel"
  if [[ ! -f "$up" ]]; then
    echo "$rel" >> "$OUT/NEW_FILES.txt"
    n_new=$((n_new + 1))
    continue
  fi
  if cmp -s "$up" "$f"; then
    echo "WARN: $rel is identical to upstream — full copy is redundant" >&2
    n_same=$((n_same + 1))
    continue
  fi
  mkdir -p "$OUT/$(dirname "$rel")"
  # labels a/<rel> b/<rel> make the diff applicable with `patch -p1 -d <kicad_src>`; the
  # banner line before the header is ignored by patch(1)
  { echo "$BANNER"; diff -u --label "a/$rel" --label "b/$rel" "$up" "$f" || true; } > "$OUT/$rel.diff"
  n_patch=$((n_patch + 1))
  patch_lines=$((patch_lines + $(wc -l < "$OUT/$rel.diff")))
  full_lines=$((full_lines + $(wc -l < "$f")))
done < <(git ls-files "$PATCHED_ROOT/**")

# ---- round-trip gate: pristine + series must reproduce the full copies -----
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
while IFS= read -r p; do
  rel="${p#$OUT/}"; rel="${rel%.diff}"
  mkdir -p "$TMP/$(dirname "$rel")"
  cp "$UPSTREAM_ROOT/$rel" "$TMP/$rel"
  patch -s -p1 -d "$TMP" < "$p"
  if ! cmp -s "$TMP/$rel" "$PATCHED_ROOT/$rel"; then
    echo "ROUND-TRIP FAILED: $rel (pristine + patch != full copy)" >&2
    exit 1
  fi
done < <(find "$OUT" -name '*.diff')

echo "upstream-diff OK: $n_patch diffs ($patch_lines lines) for $full_lines lines of full copies"
echo "new files (ours, shipped as-is): $n_new — see $OUT/NEW_FILES.txt"
[[ $n_same -eq 0 ]] || echo "WARN: $n_same redundant identical copies (see stderr)"
echo "round-trip verified: pristine + diffs == full copies (byte-identical)"
